# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_BASICAUTH: false
    links:
      - mongo  
    ports:
      - 8081:8081  