services:
  db:
    container_name: mysql_container
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - my_network

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data 

networks:
  my_network:
    driver: bridge

